---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quote-backend-git
spec:
  type: git
  params:
    - name: url
      value: https://wintonjkt:RahasiaDenpasar123@github.com/wintonjkt/quote-backend.git"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quote-backend-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/kabanero/quote-backend:tkn

